name: CI
on:
  push:
    branches: [master]

jobs:
  test:
    name: Test Release Candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: make install

      - name: Test
        run: make test

      - name: Make release candidate
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            const last_full_release_details = await github.repos.getLatestRelease({owner: context.repo.owner, repo: context.repo.repo});
            const next_release = last_full_release_details.data.tag_name.split('.').map((el, index) => {if (index == 2) { el++; } return `${el}`;}).join('.');
            const tag_name = `${next_release}-rc.${Math.round((new Date()).getTime() / 1000)}`;

            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              draft: true,
              prerelease: true,
              name: `Release Candidate ${tag_name}`,
              tag_name,
              target_commitish: context.sha,
              body: "Release Candidate"
            });
