name: Publish Release Artifacts
on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Generate artifacts
        uses: skx/github-action-build@master
        with:
          builder: .github/make-build.sh

      - name: Publish artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'terraform-provider-remotefile-*'
