name: Publish Release Artifacts
on:
  release:
    types: [created]

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Generate artifacts
        uses: skx/github-action-build@master
        with:
          builder: .github/make-build.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: "terraform-provider-remotefile-*"

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Publish artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'terraform-provider-remotefile-*'
