name: Release Published
on:
  release:
    types: [created]

jobs:
  test:
    name: Remove other release candidates
    runs-on: ubuntu-latest
    steps:
      - name: Make release candidate
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            const the_current_release = await github.repos.getLatestRelease({owner: context.repo.owner, repo: context.repo.repo});

            const next_release = last_full_release_details.data.tag_name.split('.').map((el, index) => {if (index == 2) { el++; } return `${el}`;}).join('.');
            const next_release_candidate = "${next_release}-rc."
            const next_release_candidate_tag = `${Math.round((new Date()).getTime() / 1000)}`;

            const allReleases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log(allReleases.filter((release) => release.tag_name.includes(next_release_candidate) && release.prerelease));
