name: Test Release
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: make install

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Get Commit Version
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            const date = new Date(commit_details.data.author.date)
            const ver = `${date.getFullYear()}.${(date.getMonth()+1)}.${date.getDate()}-${date.getHours()}.${date.getMinutes()}`

            octokit.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              draft: true,
              prerelease: false,
              name: `Release ${steps.author-date.outputs.result}`,
              tag_name: ver,
              target_commitish: context.sha,
            });

            return nil;
