name: Go
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: make install

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Get Commit Date
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.author-date.outputs.result }}
          release_name: Release ${{ steps.author-date.outputs.result }}
          draft: false
          prerelease: false
