name: Continuous Integration
on:
  release:
    types: [created]

jobs:
  test:
    name: Release Candidate Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: make install

      - name: Generate artefacts
        uses: skx/github-action-build@master
        with:
          builder: scripts/build.sh

      - name: Publish artefacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        with:
          args: 'terraform-provider-remotefile-*'
